export const FIFA_RANKINGS = { // Below are the rankings of 48 teams that have qualified for the FIFA World Cup 2026. The rankings are based on the FIFA World Rankings as of Apr 2026.
  ARG: { name: "Argentina", ranking: 1 },
  ESP: { name: "Spain", ranking: 2 },
  FRA: { name: "France", ranking: 3 },
  ENG: { name: "England", ranking: 4 },
  POR: { name: "Portugal", ranking: 5 },
  BRA: { name: "Brazil", ranking: 6 },
  MAR: { name: "Morocco", ranking: 7 },
  NED: { name: "Netherlands", ranking: 8 },
  BEL: { name: "Belgium", ranking: 9 },
  GER: { name: "Germany", ranking: 10 },
  CRO: { name: "Croatia", ranking: 11 },
  COL: { name: "Colombia", ranking: 13 },
  MEX: { name: "Mexico", ranking: 14 },
  SEN: { name: "Senegal", ranking: 15 },
  URU: { name: "Uruguay", ranking: 16 },
  USA: { name: "United States", ranking: 17 },
  JPN: { name: "Japan", ranking: 18 },
  SUI: { name: "Switzerland", ranking: 19 },
  IRN: { name: "Iran", ranking: 20 },
  KOR: { name: "South Korea", ranking: 22 },
  ECU: { name: "Ecuador", ranking: 23 },
  AUS: { name: "Australia", ranking: 24 },
  AUT: { name: "Austria", ranking: 25 },
  SWE: { name: "Sweden", ranking: 26 },
  CAN: { name: "Canada", ranking: 30 },
  CZE: { name: "Czechia", ranking: 32 },
  PAN: { name: "Panama", ranking: 34 },
  TUR: { name: "Türkiye", ranking: 35 },
  EGY: { name: "Egypt", ranking: 36 },
  CIV: { name: "Ivory Coast", ranking: 38 },
  SCO: { name: "Scotland", ranking: 39 },
  TUN: { name: "Tunisia", ranking: 40 },
  PAR: { name: "Paraguay", ranking: 41 },
  ALG: { name: "Algeria", ranking: 42 },
  NOR: { name: "Norway", ranking: 44 },
  KSA: { name: "Saudi Arabia", ranking: 53 },
  QAT: { name: "Qatar", ranking: 58 },
  RSA: { name: "South Africa", ranking: 59 },
  GHA: { name: "Ghana", ranking: 60 },
  IRQ: { name: "Iraq", ranking: 63 },
  UZB: { name: "Uzbekistan", ranking: 66 },
  COD: { name: "DR Congo", ranking: 67 },
  JOR: { name: "Jordan", ranking: 71 },
  CPV: { name: "Cabo Verde", ranking: 73 },
  BIH: { name: "Bosnia and Herzegovina", ranking: 74 },
  CUW: { name: "Curaçao", ranking: 82 },
  HAI: { name: "Haiti", ranking: 83 },
  NZL: { name: "New Zealand", ranking: 85 }
};
